### ISSUE TITLE
Can't build unordered_map_test.cpp with -DBASKET_ENABLE_THALLIUM_TCP

### ISSUE THREAD

**Issue by ChristopherHogan** [hariharan-devarajan/basket#2]
Does `unordered_map_test.cpp` only work with `rpclib`? I'm using the `basket-0.0.2` branch.

```
[ 87%] Building CXX object test/CMakeFiles/unordered_map_test.dir/unordered_map_   test.cpp.o
In file included from /home/chogan/basket/test/unordered_map_test.cpp:33:0:
/home/chogan/basket/include/basket/unordered_map/unordered_map.h:141:49: error:    ‘std::vector<std::pair<_T1, _T2> > basket::unordered_map<KeyType, MappedType>::L   ocalGetAllDataInServer()’ cannot be overloaded
     std::vector<std::pair<KeyType, MappedType>> LocalGetAllDataInServer();
                                                 ^~~~~~~~~~~~~~~~~~~~~~~
etc.
```

**Comment by Keith-Bateman** [comment]
I'm not sure if this is the same problem you're encountering, but the proper build process should be "cmake -DBASKET_ENABLE_THALLIUM_TCP=true .", so please try again with that and latest release (I've already updated the README and CMakeLists to indicate this).

**Comment by ChristopherHogan** [comment]
Unfortunately that did not solve the issue. It appears that the member function `LocalGetAllDataInServer` is declared twice in the same class (as the error message above implies). Once in `basket/include/basket/unordered_map/unordered_map.h:141` and again in `basket/include/basket/unordered_map/unordered_map.h:107`.

**Comment by Keith-Bateman** [comment]
Thanks. I removed duplicate declarations.

**Comment by ChristopherHogan** [comment]
Thank you. I'm still seeing an error about `MSGPACK_DEFINE`. Is `MessagePack` required for the `Thallium` version or just the `rpclib` version? It wasn't listed in the dependencies.

**Comment by Keith-Bateman** [comment]
Should only be required for rpclib version (rpclib uses it internally for serialization). I added conditional compilation around all the structures in the library, but I missed the one in the test. Added them just now.

**Comment by ChristopherHogan** [comment]
It's working now. Thanks for your help!
